services:
  - type: web
    name: yt-downloader-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000  # Ya 8080, match with your Flask app
